# Generated by Django 3.2.5 on 2021-08-27 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.IntegerField(choices=[(0, 0), (10, 10), (20, 20), (30, 30), (40, 40), (50, 50)], default=0)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('processor_manufacturer', models.CharField(blank=True, choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=200, null=True)),
                ('processor_type', models.CharField(blank=True, choices=[('i3', 'i3'), ('i5', 'i5'), ('i7', 'i7'), ('i9', 'i9'), ('Ryzen 3', 'Ryzen 3'), ('Ryzen 5', 'Ryzen 5'), ('Ryzen 7', 'Ryzen 7'), ('Ryzen 9', 'Ryzen 9')], max_length=200, null=True)),
                ('processor_model', models.CharField(blank=True, max_length=200, null=True)),
                ('gpu', models.CharField(blank=True, choices=[('Integrated', 'Integrated'), ('Dedicated', 'Dedicated')], max_length=200, null=True)),
                ('gpu_manufacturer', models.CharField(blank=True, choices=[('NVIDIA', 'NVIDIA'), ('AMD', 'AMD')], max_length=200, null=True)),
                ('gpu_model', models.CharField(blank=True, max_length=200, null=True)),
                ('gpu_vram_type', models.CharField(blank=True, choices=[('DDR5', 'DDR5'), ('DDR6', 'DDR6')], max_length=200, null=True)),
                ('ram_type', models.CharField(blank=True, choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4')], max_length=200, null=True)),
                ('ram_memory', models.CharField(blank=True, choices=[('4', '4'), ('8', '8'), ('16', '16'), ('32', '32'), ('64', '64')], max_length=200, null=True)),
                ('ram_frequency', models.CharField(blank=True, choices=[('1600', '1600'), ('2133', '2133'), ('2400', '2400'), ('2600', '2600'), ('2666', '2666'), ('3200', '3200'), ('3600', '3600')], max_length=200, null=True)),
                ('storage_type', models.CharField(blank=True, choices=[('HDD', 'HDD'), ('SSD', 'SSD')], max_length=200, null=True)),
                ('storage', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('county', models.CharField(max_length=200, null=True)),
                ('zipcode', models.CharField(max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
    ]
